-- ============================================================
-- MI Little Care — Phase X follow-up: restore parent SELECT on
-- emergency_contacts.
--
-- Diagnoses: live preview as parent Jeff (family
-- b9dc73ee-bb39-45a2-a97e-1095433dcec0) — INSERTs fire the
-- provider state-change notification email every time (so the
-- write path is exercised) but the parent's emergency-contact list
-- shows "No emergency contacts listed yet" even for contacts
-- known to exist in the DB. Reads return empty. Same shape
-- query works for `children` for the same parent on the same page,
-- so the difference must be on the emergency_contacts side.
--
-- Hypothesis (best-effort given no production DB access):
-- the parent SELECT RLS policy on emergency_contacts in
-- production is missing, broken, or different from what migration
-- 016 documents. Migration 031 made no SELECT-affecting change to
-- this table, so the trigger is most likely an out-of-band
-- production edit or a long-pre-existing drift that only became
-- visible now that Phase X exercises the parent emergency-contact
-- UI actively.
--
-- This migration: defensively re-asserts (drop-if-exists + create)
-- the parent SELECT policy that migration 016 documents. This is:
--   - Idempotent. If the policy is already correct, drop-then-create
--     replaces with the identical definition — no behavior change.
--   - Restorative. If the policy was missing, modified, or had a
--     different USING clause in production, this fixes it back to
--     the documented family-linked shape.
--   - Lockdown-preserving. This migration ONLY touches the parent
--     SELECT policy. It does NOT re-create the parent DELETE policy
--     that migration 031 intentionally dropped (the
--     upload-but-never-delete lockdown stays intact).
--   - INSERT/UPDATE unchanged. Production parent INSERT + UPDATE
--     policies are left exactly as migration 016 + 031 left them.
--
-- DEPENDENCY: applies AFTER migration 031.
--
-- ── DIAGNOSTIC QUERIES — RUN FIRST, BEFORE APPLYING THIS MIGRATION ──
--
-- These confirm or refute the root cause hypothesis. Paste each in
-- the Supabase web SQL Editor (running as service-role / admin —
-- bypasses RLS so we can see actual state) and screenshot the result.
--
-- 1) What columns does emergency_contacts ACTUALLY have in production?
--    Should include at minimum: id, user_id, family_id, relationship,
--    phone, created_at, pickup_authorized (added by 031). Whether it
--    has `name` (per migration 016) vs `first_name`+`last_name` (what
--    the parent UI writes today) is the key question for the write
--    path. The read fix below does not depend on the answer here, but
--    Seth needs to know whether the parent INSERT is silently failing.
--
--      SELECT column_name, data_type, is_nullable, column_default
--        FROM information_schema.columns
--       WHERE table_schema='public' AND table_name='emergency_contacts'
--       ORDER BY ordinal_position;
--
-- 2) Do rows actually exist for Jeff's family?
--
--      SELECT id, family_id, user_id,
--             coalesce(name, first_name || ' ' || coalesce(last_name,''))
--               AS display_name,
--             phone, created_at, pickup_authorized
--        FROM public.emergency_contacts
--       WHERE family_id = 'b9dc73ee-bb39-45a2-a97e-1095433dcec0'
--       ORDER BY created_at DESC;
--
--    If this returns rows → writes ARE succeeding, the bug is the
--    parent's read RLS (confirmed). Continue with this migration.
--
--    If it returns zero rows → writes are silently failing (column
--    mismatch most likely). This migration's read fix is still
--    correct + safe but won't be sufficient — a separate fix to the
--    parent INSERT shape is needed. Stop, report back, do not merge
--    this migration alone.
--
-- 3) What RLS policies currently exist on emergency_contacts?
--
--      SELECT polname, polcmd, qual::text AS using_clause,
--             with_check::text AS with_check_clause
--        FROM pg_policy p
--        JOIN pg_class c ON c.oid = p.polrelid
--        JOIN pg_namespace n ON n.oid = c.relnamespace
--       WHERE n.nspname='public' AND c.relname='emergency_contacts'
--       ORDER BY polcmd, polname;
--
--    Expected after migration 016 + 031:
--      - "Parents can insert emergency contacts"           (INSERT)
--      - "Parents can update emergency contacts"           (UPDATE)
--      - "Parents can view emergency contacts for their families" (SELECT)
--      - "Staff can view their licensee's emergency contacts"     (SELECT)
--      - "Users can delete their own emergency_contacts"   (DELETE — provider only, gates on user_id)
--      - "Users can insert their own emergency_contacts"   (INSERT)
--      - "Users can update their own emergency_contacts"   (UPDATE)
--      - "Users can view their own emergency_contacts"     (SELECT)
--    Migration 031 dropped:
--      - "Parents can delete emergency contacts"           (DELETE) — stays dropped.
--
--    If the "Parents can view emergency contacts for their families"
--    SELECT policy is MISSING or has a different `using_clause` than
--    the one in this migration → confirms the hypothesis. This
--    migration restores it.
--
--    If it exists with the correct using_clause → the root cause is
--    something else. Stop. Investigate further before applying.
--
-- ── EXPECTED VERIFICATION (run AFTER applying this migration) ──
--
--   SELECT polname, polcmd FROM pg_policies
--    WHERE schemaname='public'
--      AND tablename='emergency_contacts'
--      AND polname = 'Parents can view emergency contacts for their families';
--   -- expect: one row, polcmd = SELECT.
--
--   SELECT polname FROM pg_policies
--    WHERE schemaname='public'
--      AND tablename='emergency_contacts'
--      AND polcmd = 'DELETE'
--      AND polname like 'Parents can%';
--   -- expect: zero rows (the lockdown stays intact).
--
-- ── LIVE GATE (run as parent Jeff on preview, AFTER apply) ──
--
--   1. Open /parent/my-family → Emergency tab.
--      - Previously-saved contacts for Jeff's family appear in the
--        list (rather than "No emergency contacts listed yet").
--   2. Add a new emergency contact via the parent UI.
--      - The new row appears immediately (no reload).
--      - Exactly one row is added per save click (no duplicates).
--   3. As parent Jeff, attempt DELETE on emergency_contacts via direct
--      PostgREST. Expect 0 rows affected (the lockdown holds — this
--      migration did NOT re-introduce DELETE).
--
-- ============================================================

-- -------------------------------------------------------
-- 1. Re-assert the parent SELECT policy.
-- -------------------------------------------------------
-- Idempotent drop-then-create with the exact USING clause from
-- migration 016. Family-linked: a parent sees emergency_contacts
-- rows whose `family_id` appears in the parent's active
-- parent_family_links.
drop policy if exists "Parents can view emergency contacts for their families"
  on public.emergency_contacts;
create policy "Parents can view emergency contacts for their families"
  on public.emergency_contacts for select
  to authenticated
  using (
    family_id in (
      select parent_family_links.family_id
        from public.parent_family_links
       where parent_family_links.parent_id = auth.uid()
         and parent_family_links.status    = 'active'
    )
  );

-- ============================================================
-- DOWN MIGRATION (commented; uncomment + run if rollback is needed)
-- ============================================================
-- Rolling back this migration drops the parent SELECT policy on
-- emergency_contacts. After rollback, parents would lose visibility
-- to their family's emergency contacts entirely (unless the
-- original policy is re-created via another path). The provider's
-- SELECT policies are unaffected.
--
-- drop policy if exists "Parents can view emergency contacts for their families"
--   on public.emergency_contacts;
